[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Ryan Widmaier <ryan.widmaier@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyparsing = "^3.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
